const makesAndModels = {
    "Audi": ["A1", "A3", "A4", "A6", "A8", "Q2", "Q3", "Q5", "Q7", "Q8", "e-tron", "RS"],
    "Ashok Leyland": ["Dost", "Partner", "Stile"],
    "Bentley": ["Bentayga", "Continental", "Flying Spur"],
    "BMW": ["1 Series", "2 Series", "3 Series", "4 Series", "5 Series", "6 Series", "7 Series", "8 Series", "X1", "X2", "X3", "X4", "X5", "X6", "X7", "Z4", "i3", "i8", "M"],
    "Bugatti": ["Chiron", "Divo"],
    "BYD": ["e6", "Tang", "Yuan"],
    "Chevrolet": ["Beat", "Cruze", "Enjoy", "Sail", "Spark", "Tavera"],
    "Citroen": ["Berlingo", "C5 Aircross"],
    "Datsun": ["GO", "GO+"],
    "Ferrari": ["488", "812", "California", "Portofino", "Roma", "SF90 Stradale"],
    "Fiat": ["500", "Abarth", "Avventura", "Linea", "Urban Cross"],
    "Force": ["Gurkha", "Traveller"],
    "Ford": ["Aspire", "EcoSport", "Endeavour", "Figo", "Freestyle"],
    "Honda": ["Amaze", "BR-V", "City", "Civic", "CR-V", "Jazz", "WR-V"],
    "Hyundai": ["Aura", "Creta", "Elantra", "Grand i10", "i20", "i20 Active", "Kona Electric", "New Santro", "Tucson", "Venue", "Verna", "Xcent"],
    "Isuzu": ["D-Max", "MUX"],
    "Jaguar": ["XE", "XF", "XJ", "F-PACE", "F-TYPE"],
    "Jeep": ["Compass", "Wrangler"],
    "Kia": ["Carnival", "Seltos", "Sonet", "Sportage", "Stinger"],
    "Lamborghini": ["Aventador", "Huracan", "Urus"],
    "Land Rover": ["Discovery", "Discovery Sport", "Range Rover", "Range Rover Evoque", "Range Rover Sport", "Range Rover Velar"],
    "Lexus": ["ES", "IS", "LC", "LS", "LX", "NX", "RX", "UX"],
    "Mahindra": ["Alturas G4", "Bolero", "e2o", "eVerito", "KUV100", "Marazzo", "NuvoSport", "Scorpio", "Thar", "TUV300", "TUV300 Plus", "Verito", "XUV300", "XUV500", "Xylo"],
    "Maserati": ["Ghibli", "Levante", "Quattroporte"],
    "Maruti Suzuki": ["Alto", "Baleno", "Celerio", "Ciaz", "Dzire", "Eeco", "Ertiga", "Ignis", "S-Presso", "Swift", "Vitara Brezza", "Wagon R", "XL6"],
    "MG Motors": ["Gloster", "Hector", "ZS EV"],
    "Mini": ["Cooper", "Countryman", "Convertible"],
    "Mitsubishi": ["Outlander", "Pajero Sport"],
    "Nissan": ["Kicks", "Magnite", "Micra", "Sunny", "Terrano"],
    "Porsche": ["911", "Cayenne", "Macan", "Panamera", "Taycan"],
    "Renault": ["Duster", "Kwid", "Triber"],
    "Rolls Royce": ["Cullinan", "Dawn", "Ghost", "Phantom", "Wraith"],
    "Skoda": ["Kodiaq", "Octavia", "Rapid", "Superb"],
    "Tata Motors": ["Altroz", "Harrier", "Hexa", "Nexon", "Safari", "Tiago", "Tigor"],
    "Toyota": ["Camry", "Corolla Altis", "Fortuner", "Glanza", "Innova Crysta", "Yaris"],
    "Volkswagen": ["Ameo", "Polo", "Tiguan Allspace", "Vento"],
    "Volvo": ["S60", "S90", "V40", "V60", "XC40", "XC60", "XC90"]
  };
  
  export default makesAndModels;
  